config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  resources :stands
  resources :plants
  root to: 'visitors#index'
  
  namespace :api do
    resources :plants
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plant.rb
class Plant < ActiveRecord::Base
  validates :latin_name, presence: true

  def get
    Plant.all
  end
end

app/models/stand.rb
class Stand < ActiveRecord::Base

  def coords
    stands.select('min_long', 'max_long', 'min_lat', 'max_lat')
  end

  def stands
    @stands = Stand.all
  end
end

app/controllers/api/plants_controller.rb
class Api::PlantsController < ApplicationController
  def index
    render json: Plant.all
  end

  def show
    list = Plant.find(params[:id])
    render json: list
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  def index
    @hello_world_props = coords.to_json
  end

  def coords
    stands.select('min_long', 'max_long', 'min_lat', 'max_lat')
  end

  def stands
    @stands = Stand.all
  end

end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  def index
    render json: Plant.all
  end

  def show
    render json: Plant.find(id)
  end

  def new
    @plant = Plant.new
  end

  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def id
      params.fetch(:id)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
      params.require(:plant).permit(:latin_name, :common_name, :habitat)
    end
end

app/controllers/stands_controller.rb
class StandsController < ApplicationController
  before_action :set_stand, only: [:show, :edit, :update, :destroy]

  # GET /stands
  # GET /stands.json
  def index
    @stands_props = stands
    @stands_coords = coords.as_json
  end

  # GET /stands/1
  # GET /stands/1.json
  def show
  end

  # GET /stands/new
  def new
    @stand = Stand.new
    @common_names = common_names
  end

  def plant_response
    Plant.new().get
  end

  def coords
    stands.select('min_long', 'max_long', 'min_lat', 'max_lat')
  end

  # GET /stands/1/edit
  def edit
  end

  # POST /stands
  # POST /stands.json
  def create
    @stand = Stand.new(stand_params)

    respond_to do |format|
      if @stand.save
        format.html { redirect_to @stand, notice: 'Stand was successfully created.' }
        format.json { render :show, status: :created, location: @stand }
      else
        format.html { render :new }
        format.json { render json: @stand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stands/1
  # PATCH/PUT /stands/1.json
  def update
    respond_to do |format|
      if @stand.update(stand_params)
        format.html { redirect_to @stand, notice: 'Stand was successfully updated.' }
        format.json { render :show, status: :ok, location: @stand }
      else
        format.html { render :edit }
        format.json { render json: @stand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stands/1
  # DELETE /stands/1.json
  def destroy
    @stand.destroy
    respond_to do |format|
      format.html { redirect_to stands_url, notice: 'Stand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def common_names
      plants.map do |plant|
        plant.select { |key, value| key.match('common_name') }.map{ |k,v| v }
      end.flatten
    end

    def plants
      @plant ||= plant_response.as_json
    end

    def stands
      @stands = Stand.all
    end

  
    # Use callbacks to share common setup or constraints between actions.
    def set_stand
      @stand = Stand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stand_params
      params.require(:stand).permit(:max_lat, :min_lat, :max_long, :min_long)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("StandsApp", props: @hello_world_props, prerender: false) %>

app/views/layouts/_navigation.html.erb
 <div class="container">      
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Overview', root_path %></li>
      <li><%= link_to 'Stands', stands_path %></li>
      <li><%= link_to 'Plants', plants_path %></li>
    </ul>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Stands', stands_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <title><%= content_for?(:title) ? yield(:title) : "PT" %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDw25Rma6yRtHUCxur9KyaG6peisvMQapo&sensor=false">
  </script>


</head>
<body class="<%= body_class %>">
  <header class="navbar nav-tabs navbar-inverse">
    <%= render 'layouts/navigation' %>
  </header>
  <main role="main">
      <%= render "flashes" -%>
    <%= yield %>
      <%= render "javascript" %>
  </main>
</body>
</html>

app/views/pages/about.html.erb
About

app/views/plants/_form.html.erb
<%= form_for(@plant) do |f| %>
  <% if @plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% @plant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latin_name %><br>
    <%= f.text_field :latin_name %>
  </div>
  <div class="field">
    <%= f.label :common_name %><br>
    <%= f.text_field :common_name %>
  </div>
  <div class="field">
    <%= f.label :habitat %><br>
    <%= f.text_field :habitat %>
  </div>
  <div class="actions">
    <%= f.submit 'Add Plant' %>
  </div>
<% end %>

app/views/plants/edit.html.erb
<h1>Editing Plant</h1>

<%= render 'form' %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<h1>Temperate Wild Plants</h1>

<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th>id</th>
      <th>Latin name</th>
      <th>Common name</th>
      <th>Habitat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plants.each do |plant| %>
      <tr>
        <td><%= plant.id %></td>
        <td><%= plant.latin_name %></td>
        <td><%= plant.common_name %></td>
        <td><%= plant.habitat %></td>
        <td><%= link_to 'Show', plant %></td>
        <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
        <td><%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Plant', new_plant_path %>

app/views/plants/new.html.erb
<h1>New Plant</h1>

<%= render 'form' %>

<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<h1><%= @plant.common_name %></h1>

<p>
  <strong>Latin name:</strong>
  <%= @plant.latin_name %>
</p>

<p>
  <strong>Common name:</strong>
  <%= @plant.common_name %>
</p>

<p>
  <strong>Habitat:</strong>
  <%= @plant.habitat %>
</p>

<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %>

app/views/stands/_form.html.erb
<%= form_for(@stand) do |f| %>
  <% if @stand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stand.errors.count, "error") %> prohibited this stand from being saved:</h2>

      <ul>
      <% @stand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :max_lat, "Max Lat (north)" %><br>
    <%= f.number_field :max_lat, step: :any %>
  </div>
  <div class="field">
    <%= f.label :min_lat, "Min Lat (south)" %><br>
    <%= f.number_field :min_lat, step: :any %>
  </div>
  <div class="field">
    <%= f.label :max_long, "Max Long (west)" %><br>
    <%= f.number_field :max_long, step: :any %>
  </div>
  <div class="field">
    <%= f.label :min_long, "Min Long (east)"%><br>
    <%= f.number_field :min_long, step: :any %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stands/edit.html.erb
<h1>Editing Stand</h1>

<%= render 'form' %>

<%= link_to 'Show', @stand %> |
<%= link_to 'Back', stands_path %>

app/views/stands/index.html.erb
<%= react_component('StandsApp', props: { areas: @stands_coords }) %>
 
<% content_for :title do %>Stands<% end %>

<h1>Listing Stands</h1>

<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th>max_long</th>
      <th>min_long</th>
      <th>max_lat</th>
      <th>min_lat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stands.each do |stand| %>
      <tr>
        <td><%= stand.max_long %></td>
        <td><%= stand.min_long %></td>
        <td><%= stand.max_lat %></td>
        <td><%= stand.min_lat %></td>
        <td><%= link_to 'Show', stand %></td>
        <td><%= link_to 'Edit', edit_stand_path(stand) %></td>
        <td><%= link_to 'Destroy', stand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stand', new_stand_path %>

app/views/stands/new.html.erb
<h1>New Stand</h1>

<%= render 'form' %>

<%= link_to 'Back', stands_path %>

app/views/stands/show.html.erb
<%= link_to 'Edit', edit_stand_path(@stand) %> |
<%= link_to 'Back', stands_path %>

<div>
<% content_for :title do %><%= @stand.id %><% end %>

  <script>
    function initMap() {
      var map;

      var mapOptions = {
        center: new google.maps.LatLng(<%= @stand.max_lat %>, <%= @stand.max_long %>),
        zoom: 13,
        mapTypeId: google.maps.MapTypeId.HYBRID
      };

      map = new google.maps.Map(document.getElementById("map"), mapOptions);
      google.maps.event.addDomListener(window, "resize", function() {
         var center = map.getCenter();
         google.maps.event.trigger(map, "resize");
         map.setCenter(center);
      });

      var area_1 = new google.maps.Rectangle({
        strokeColor: '#FF0000',
        strokeOpacity: 0.8,
        strokeWeight: 2,
        fillColor: '#FF0000',
        fillOpacity: 0.35,
        map: map,
        bounds: {
          north: <%= @stand.max_lat %>,
          south: <%= @stand.min_lat %>,
          west: <%= @stand.max_long %>,
          east: <%= @stand.min_long %>
        }
      });
    }

    document.addEventListener("DOMContentLoaded", function() {
      initMap();
    });
  </script>

    <div style="float:left; display:inline-block;">
      <div id="map"></div>
    </div>

    <div style="float:left; margin-left:10px; display:inline-block;">

      <div style="float:left; display:inline-block;">
        <a href="#">View Timeline</a>
      </div>
    </div>

    <br/>
</div>

app/views/visitors/index.html.erb
<% content_for :title do %>All The Plants<% end %>
  <body>  
   <div style="float:left; display:inline-block;">
      <div id="map2" style="width:500px;height:300px"></div>
    </div>

    <div style="float:left; margin-left:10px; display:inline-block;">
      Global GeoGrow
      <label>Founded by: Someone</label>
      <label>Location: 53.393, -2.187</label> 
      <label>Habitat: <b>Industrial Estate</b></label>
      <label>Number of Edible Species: 1</label> 
      <label>Next harvest due: <b>2016 June</b></label> 
      <label>Last observation: Gather35 found <b>ripening</b> Mugwort in <b>2016 May</b></label> 
      <label>Last interaction:  Gather35 <b>harvested</b> Mugwort in <b>2015 June</b></label>
      
      <div style="float:left; display:inline-block;">
        <a href="#">Add a new Observation</a> |
        <a href="#">Add a new Interaction</a><br/>
        <a href="#">View Timeline</a> |
        <a href="#">Rate Suitability</a><br/>
      </div>
    </div>
    <br/>
  </body>
</html>

<script>
  function initMap() {
    var map, map2, map3;

    var mapOptions = {
      center: new google.maps.LatLng(53.393,-2.187),
      zoom: 13,
      mapTypeId: google.maps.MapTypeId.HYBRID
    };

    //map = new google.maps.Map(document.getElementById("map"), mapOptions);
    map2 = new google.maps.Map(document.getElementById("map2"), mapOptions);
    //map3 = new google.maps.Map(document.getElementById("map3"), mapOptions);

    //var marker = new google.maps.Marker({ map: map, position: { lat: 53.393, lng: -2.187} });
    var marker2 = new google.maps.Marker({ map: map2, position: { lat: 53.393, lng: -2.187 } });
    var marker2b = new google.maps.Marker({ map: map2, position: { lat: 53.3935, lng: -2.1781 } });
    //var marker3 = new google.maps.Marker({ map: map3, position: { lat: 57.245, lng: -2.311 } });
    //var marker3b = new google.maps.Marker({ map: map3, position: { lat: 57.245, lng: -2.290 } });

    var area_1 = new google.maps.Rectangle({
      strokeColor: '#FF0000',
      strokeOpacity: 0.8,
      strokeWeight: 2,
      fillColor: '#FF0000',
      fillOpacity: 0.35,
      map: map,
      bounds: {
        north: 53.394,
        south: 53.392,
        east: -2.185,
        west: -2.189
      }
    });

    var area_2 = new google.maps.Rectangle({
      strokeColor: '#FF0000',
      strokeOpacity: 0.8,
      strokeWeight: 2,
      fillColor: '#FF0000',
      fillOpacity: 0.35,
      map: map3,
      bounds: {
        north: 53.395,
        south: 53.393,
        east: -2.176,
        west: -2.181
      }
    });

    var area_1_3 = new google.maps.Rectangle({
      strokeColor: '#FF0000',
      strokeOpacity: 0.8,
      strokeWeight: 2,
      fillColor: '#FF0000',
      fillOpacity: 0.35,
      map: map3,
      bounds: {
        north: 53.394,
        south: 53.392,
        east: -2.185,
        west: -2.189
      }
    });
  }

  document.addEventListener('DOMContentLoaded', initMap(), false);
    
</script>